feat(modules/cloud-logs): introduce cloud logs module for s3 onboarding
sysdiglabs/terraform-aws-secure pull request #16
Opened 2024-09-17 10:59 UTC by SKosier

2024-09-19 13:31 UTC, mancia93 approved these changes
LGTM 🚀

2024-09-19 14:43 UTC, legobrick requested changes

2024-09-19 14:43 UTC, legobrick commented on modules/integrations/cloud-logs/README.md
> +| <a name="input_sysdig_secure_account_id"></a> [sysdig\_secure\_account\_id](#input\_sysdig\_secure\_account\_id) | (Required) ID of the Sysdig Cloud Account to enable Event Bridge integration for (
```suggestion
| <a name="input_sysdig_secure_account_id"></a> [sysdig\_secure\_account\_id](#input\_sysdig\_secure\_account\_id) | (Required) ID of the Sysdig Cloud Account to enable Cloud Logs integration for (incase of organization, ID of the Sysdig management account) | `string` | n/a | yes |
```

2024-09-19 14:43 UTC, legobrick commented on modules/integrations/cloud-logs/README.md
> +| <a name="input_bucket_arn"></a> [bucket\_arn](#input\_bucket\_arn) | (Required) The ARN of your s3 bucket associated with your Cloudtrail trail
```suggestion
| <a name="input_bucket_arn"></a> [bucket\_arn](#input\_bucket\_arn) | (Required) The ARN of your S3 bucket associated with your CloudTrail Trail                                                                     | `string` | n/a                                                         |   yes    |
```

2024-09-19 14:43 UTC, legobrick commented on modules/integrations/cloud-logs/main.tf
> +# Call Sysdig Backend to add the event-bridge integration to the Sysdig Cloud Account
```suggestion
# Call Sysdig Backend to add the cloud logs integration to the Sysdig Cloud Account
```

2024-09-19 14:43 UTC, legobrick commented on modules/integrations/cloud-logs/README.md
> +| <a name="input_bucket_arn"></a> [bucket\_arn](#input\_bucket\_arn) | (Required) The ARN of your s3 bucket associated with your Cloudtrail trail
Should we ditch this as we move to modular, in favor of the folder arn? The bucket arn can be derived from that...

2024-09-19 14:43 UTC, legobrick commented on modules/integrations/cloud-logs/main.tf
> +        region        = var.region
Before releasing this, let's remove the region, so we avoid "polluting" some other setups and come up with something clean. Ok to keep this on a branch for internal testing for now, but let's remove it before releasing, along with the variable etc.

2024-09-19 15:02 UTC, SKosier commented on modules/integrations/cloud-logs/main.tf
> +        region        = var.region
Agree. Will open a PR that extends this one and removes the region. So we can prepare backend changes in the meantime.

2024-10-02 07:08 UTC, legobrick approved these changes

2024-10-02 10:44 UTC, merged